apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner-report-frontend

  template:
    metadata:
      labels:
        app: learner-report-frontend
    spec:
      containers:
      - name: frontend-app
        image: misscoder21/learner-report-frontend:v1
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
