apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-mongodb
  template:
    metadata:
      labels:
        app: report-mongodb
    spec:
      containers:
      - name: report-mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 500m
            memory: 512Mi

