apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.backend }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployments.backend }}
    ports:
    - port: {{ .Values.images.backend.port }}
      targetPort: {{ .Values.images.backend.port }}

