apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.frontend }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployments.frontend }}
  ports:
  - port: {{ .Values.images.frontend.port }}
    targetPort: {{ .Values.images.frontend.port }}
