apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.frontend }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.deployments.frontend }}

  template:
    metadata:
      labels:
        app: {{ .Values.deployments.frontend }}
    spec:
      containers:
      - name: {{ .Values.deployments.frontend }}
        image: "{{ .Values.images.frontend.image }}:{{ .Values.images.frontend.tag }}"
        ports:
        - containerPort: {{ .Values.images.frontend.port }}
        # resources:
        #   limits:
        #     cpu: 1000m
        #     memory: 512Mi
