apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.db }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployments.db }}
  ports:
  - port: {{ .Values.images.db.port }}
    targetPort: {{ .Values.images.db.port }}
